---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bacula-postgres-pv
  namespace: bacula
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  claimRef: 
    name: bacula-postgres-pvc
    namespace: bacula
  hostPath:
    path: /data/bacula/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bacula-postgres-pvc
  namespace: bacula
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
  accessModes: 
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bacula-postgres
  name: bacula-postgres
  namespace: bacula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula-postgres
  strategy: {}
  template:
    metadata:
      labels:
        app: bacula-postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: "techsup@2"
          - name: POSTGRES_DB
            value: bacula
          - name: POSTGRES_USER
            value: bacula
          - name: POSTGRES_INITDB_ARGS
            value: '--encoding=SQL_ASCII'
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: bacula-postgres-pvc 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-postgres
  name: bacula-postgres
  namespace: bacula
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: bacula-postgres
  type: ClusterIP
